// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: control.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KernelClient is the client API for Kernel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KernelClient interface {
	SendControlPkg(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (Kernel_SendControlPkgClient, error)
}

type kernelClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelClient(cc grpc.ClientConnInterface) KernelClient {
	return &kernelClient{cc}
}

func (c *kernelClient) SendControlPkg(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (Kernel_SendControlPkgClient, error) {
	stream, err := c.cc.NewStream(ctx, &Kernel_ServiceDesc.Streams[0], "/pb.Kernel/SendControlPkg", opts...)
	if err != nil {
		return nil, err
	}
	x := &kernelSendControlPkgClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kernel_SendControlPkgClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type kernelSendControlPkgClient struct {
	grpc.ClientStream
}

func (x *kernelSendControlPkgClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KernelServer is the server API for Kernel service.
// All implementations must embed UnimplementedKernelServer
// for forward compatibility
type KernelServer interface {
	SendControlPkg(*ControlRequest, Kernel_SendControlPkgServer) error
	mustEmbedUnimplementedKernelServer()
}

// UnimplementedKernelServer must be embedded to have forward compatible implementations.
type UnimplementedKernelServer struct {
}

func (UnimplementedKernelServer) SendControlPkg(*ControlRequest, Kernel_SendControlPkgServer) error {
	return status.Errorf(codes.Unimplemented, "method SendControlPkg not implemented")
}
func (UnimplementedKernelServer) mustEmbedUnimplementedKernelServer() {}

// UnsafeKernelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelServer will
// result in compilation errors.
type UnsafeKernelServer interface {
	mustEmbedUnimplementedKernelServer()
}

func RegisterKernelServer(s grpc.ServiceRegistrar, srv KernelServer) {
	s.RegisterService(&Kernel_ServiceDesc, srv)
}

func _Kernel_SendControlPkg_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ControlRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelServer).SendControlPkg(m, &kernelSendControlPkgServer{stream})
}

type Kernel_SendControlPkgServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type kernelSendControlPkgServer struct {
	grpc.ServerStream
}

func (x *kernelSendControlPkgServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

// Kernel_ServiceDesc is the grpc.ServiceDesc for Kernel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kernel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Kernel",
	HandlerType: (*KernelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendControlPkg",
			Handler:       _Kernel_SendControlPkg_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control.proto",
}
